# Generated by Django 6.1.1 on 2026-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('location', models.CharField(blank=True, help_text="e.g. 'Patio', 'Main Hall', 'Window'", max_length=80)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Being Cleaned')], default='available', max_length=20)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
