# Generated by Django 6.1.1 on 2026-09-15 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pcs', 'Pieces')], default='pcs', max_length=10)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Stock level at/below which this item is considered low.', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for deductions.', max_digits=10)),
                ('reason', models.CharField(choices=[('restock', 'Restock'), ('order_deduction', 'Order Deduction'), ('correction', 'Manual Correction'), ('waste', 'Waste / Spoilage')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='e.g. related order number', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
